### PR TITLE
Updated to bootstrap 3.3.2 and added bootstrap accessibility plugin

### PR DESCRIPTION
**Pull request by becka11y**
Combined the changes for feature/bootstrap and feature/bootstrapA11y into this new branch.  Since bootstrap 3.3.2 was available I upated to it.  I added the bootstrap a11y plugin. This will be used for tab panel implementation of the bookmarks UI . It also fixes the tab/shift-tab traversal of dialogs. Although there is still one extra tab stop through the URL bar that needs addressing.

### CODE REVIEW

**Comment by danielweck** [comment]
Note to self (source code diff, to double-check):
https://github.com/readium/readium-js-viewer/pull/183/files#diff-1
https://github.com/readium/readium-js-viewer/blob/feature/bootstrapA11y2/css/viewer.css
(I think that the CSS rule `background-size: auto 28px !important;` must be changed in the correct selector `.navbar .icon-logo, .navbar .icon-logo:active`, not `.navbar-right`, and there are a couple of other fixes as well)

**Comment by danielweck** [comment]
Hi @becka11y
I backported the CSS fixes from the original feature branch / Pull Request.
I've tested your code and it all seems to work as expected. 
Closing the obsolete Pull Request: https://github.com/readium/readium-js-viewer/pull/183
Deleting the obsolete feature branch: https://github.com/readium/readium-js-viewer/tree/feature/bootstrap

**Comment by danielweck** [comment]
Hello @becka11y I added missing CSS references to bootstrap-accessibility, sorry I did not catch that before:

https://github.com/readium/readium-js-viewer/commit/9e10733168930ebd37bb761de232c2fb909cafbd

**Comment by becka11y** [comment]
Thanks, Daniel - sorry I missed it. I totally forgot about simplerviewer.html!

**Comment by danielweck** [comment]
No problems @becka11y (I should have noticed that too)
PS: not just the simpleviewer, also cloud reader(s) and the chrome app!

**Pull request merged**
