### PR TITLE
package.json hack to fix #566: add symlink step to prepare script

### LINKED ISSUE #566: `npm run test:*` fails with error: "Unable to find path to phantomjs"
The automated Selenium tests do not work in current `develop` and `master` branches of new clones of the repo.  Clones made before Feb 18, 2016 might not have this bug, even if fast-forwarded to current branch heads.  The bug only manifests if `node_modules/` contains only dependencies in current `package.json`.
#### Related issue(s) and/or pull request(s)

See #567.
#### Expected Behaviour

Run tests successfully.
#### Observed behaviour

Instead, running the tests fails with error:

``` shell
> parallelshell "node build-config/selenium_webdriver.js -a 127.0.0.1 -p 8080 -c-1 ./dist/cloud-reader" "npm run mocha --readium-js-viewer:MODE=firefox"

http-server arguments: 
[ '-a', '127.0.0.1', '-p', '8080', '-c-1', './dist/cloud-reader' ]
SELENIUM ...
undefined:67
    throw new Error('Unable to find path to phantomjs, please run npm install and find the relative path for your system. Current location: [' + __dirname + ']' +

[...SNIPPED...]
```
#### Steps to reproduce

Make a new clone of `readium-js-viewer` and check out either `develop` or `master` branches.  If using an old clone made before Feb 18, 2016, fast forward to current `develop` or `master`, delete `node_modules/`, and recreate it so that it matches `package.json` dependencies exactly.

Then run any of the following (might need to do `npm run dist` first?):
- `npm run test`
- `npm run test:chrome`
- `npm run test:firefox`
### Product

The automated test suite that comes with the `readium-js-viewer` repo.
#### Additional information

Why it's happening:

[Line 42 of `build-config/selenium_webdriver.js`](https://github.com/readium/readium-js-viewer/blob/master/build-config/selenium_webdriver.js#L42):

``` JavaScript
                    var func = eval("( function(){"+fileContents+"; return {start: start, stop: stop}; } )");
```

...is slurping in [this version of grunt-selenium-webdriver's node_modules/grunt-selenium-webdriver/tasks/selenium_webdriver.js](https://github.com/levexis/grunt-selenium-webdriver/blob/b05fa674177b763bfeeab02f008f7150d525ff3e/tasks/selenium_webdriver.js), which is part of version 0.2.482 packaged for NPM.  [Lines 56-72 of this file](https://github.com/levexis/grunt-selenium-webdriver/blob/b05fa674177b763bfeeab02f008f7150d525ff3e/tasks/selenium_webdriver.js#L56-L72):

``` JavaScript

...

    phantomLoc = __dirname,

...

// installed as module or locally?
if ( fs.existsSync( phantomLoc + "/../node_modules/phantomjs/bin/phantomjs") ) {
//    console.log ('branch 1b');
    // mac as grunt plugin test
    phantomLoc += "/../node_modules/phantomjs/bin";
} else if (fs.existsSync(phantomLoc + '/../../phantomjs/bin/phantomjs')) {
    // mac, module use
//    console.log ('branch 2b');
    phantomLoc += "/../../phantomjs/bin";
} else {
    // if adding new cases please identify environment so that changes can be maintained
    throw new Error('Unable to find path to phantomjs, please run npm install and find the relative path for your system. Current location: [' + __dirname + ']' +
        'Environment: [' + os.type() + ',' +
        os.platform() + ',' +
        os.arch() + ',' +
        os.release() + ']');
}

...

```

Note that because this file is being slurped in and `eval`-ed by `build-config/selenium_webdriver.js`, that `phantomLoc` is assigned `build-config/` (by `__dirname`).  Hence, this `grunt-selenium-webdriver` task is looking for `phantomjs` in the main `node_modules/` for `readium-js-viewer`, which is in fact not there anymore, as it was replaced by `phantomjs-prebuilt` in the main `package.json` here: [2dc9bb0ee2d22f7644e60ff291afe221c576b136](https://github.com/readium/readium-js-viewer/commit/2dc9bb0ee2d22f7644e60ff291afe221c576b136).

A recent commit to `grunt-selenium-webdriver` seems to fix this problem:
[e9f63af80c8e6738b00812370c6f1ba13c5dc817](https://github.com/levexis/grunt-selenium-webdriver/commit/e9f63af80c8e6738b00812370c6f1ba13c5dc817#L57-64).  This commit is for version 0.2.530, though, and the NPM repository has only the 0.2.482 package.  It is unclear when the 0.2.530 NPM release will happen: [Github issue #29: Please release 0.2.530](https://github.com/levexis/grunt-selenium-webdriver/issues/29).

Temporary workaround options:
- Add a step to `npm prepare` that creates a symlink `node_modules/grunt-selenium-webdriver/node_modules/phantomjs` -> `node_modules/phantomjs`:

``` JavaScript
    "prepare": "npm run prepare:submodule && npm run prepare:local && cd node_modules && ln -s ../node_modules/grunt-selenium-webdriver/node_modules/phantomjs phantomjs",
```

This will match this `grunt-selenium-webdriver` condition:

``` JavaScript
if ( fs.existsSync( phantomLoc + "/../node_modules/phantomjs/bin/phantomjs") ) {
```
- Change the `grunt-selenium-webdriver` dependency in `package.json` from this:

``` json
    "grunt-selenium-webdriver": "latest",
```

...to this:

``` json
    "grunt-selenium-webdriver": "levexis/grunt-selenium-webdriver#e9f63af80c8e6738b00812370c6f1ba13c5dc817",
```

I've tested both these workarounds, and will submit a PR for the first, as that seems to be the more appropriate solution.

Even after using these workarounds, I was unable to get tests working.  Please note that there is currently a problem of integration between Selenium and Firefox:
- [Firefox driver in 2.53.4 not working with Firefox 48 #2559](https://github.com/SeleniumHQ/selenium/issues/2559)
- [Selenium 2.53 not working on Firefox 47](http://stackoverflow.com/questions/37693106/selenium-2-53-not-working-on-firefox-47)
- [Selenium 2.53.1 does not work on FireFox 48 (duplicate)](http://stackoverflow.com/questions/38748675/selenium-2-53-1-does-not-work-on-firefox-48)
- [Firefox 47 - Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. #2110](https://github.com/SeleniumHQ/selenium/issues/2110)
- [Firefox Developer Edition (47.0a2) crashes using Java Selenium 2.53.0 (and 2.52.0, 2.48.2) #1862](https://github.com/SeleniumHQ/selenium/issues/1862)

The solution at the moment seems to be either to use Firefox 47.0.1 (not 47.0 or 48.0), or to use the new, in-development [GeckoDriver](https://github.com/mozilla/geckodriver) a.k.a. [Marionette](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Marionette).  At the time I did research on this driver, it didn't seem like it was robust enough for serious use.
I've been using a parallel Firefox 47.0.1 with success with Selenium scripts for other projects.  However, because the Readium tests use `grunt-selenium-webdriver`, I was unable to figure out a way to specify an alternative Firefox or Selenium.

The Chrome tests also seem to be failing.  As I looked over the `tests/` directory I noticed that things seemed to be in flux, so decided not to pursue this any farther for the time being.

### PR DESCRIPTION
**Pull request by da70**
Hack to fix automated Selenium tests in current develop and master branches.

#### Related issue(s) and/or pull request(s)
See #566.

### CODE REVIEW

**Comment by danielweck** [comment]
thank you!
first of all, package.json is auto-generated from CSON master files (see the 'package' folder). so your changes will be overridden.
secondly, the 'ln' symbolic linking command is not cross-platform. we are working hard to keep the build process compatible with Windows DOS, by creating NodeJS scripts or by using existing NodeJS libs that implement filesystem manipulations, etc. 
I am closing this PR, but the issue you filed is definitely worth looking into. I personally have had no problems running the tests, but I will check again.
PS: try running he CFI unit tests to see if this works at your end, please (Firefox and Chrome)

**Comment by da70** [comment]
Ah yes I forgot about the CSON master files, and good point about the Windows compatibility.

I have updated the bug with more detailed instructions.  It is likely that the tests are not breaking for you because your clone was created and initialized before Feb 18, 2016.  That was the day that `phantomjs` was removed as a dependency.  If you delete that module and try running your tests again you will likely get the bug.  Or, you could make a completely new clone and run the tests (that's how I discovered the problem), or else delete `node_modules/` completely and re-build it.

I will try the CFI unit tests.  Thanks!

**Comment by danielweck** [comment]
awesome feedback, thanks!

**Comment by da70** [comment]
Sure.  Also, I ran the CFI tests.  At first they failed due to missing peer dependency `jasmine-core`.  I checked the latest Travis build job for `develop` -- [Job # 137.1](https://travis-ci.org/readium/readium-cfi-js/jobs/156214951) -- and noted that it used older versions of Node and NPM (v0.12.15 and v2.15.1, respectively).  That's when I remembered that we can't use a Node version > 4.x due to #453.  I've been using 6.0.0 with its higher NPM version.

I installed Node 0.12.15 and was able to initialize a new clone of `readium-cfi-js` and run all tests with 0 failures.  I then switched to Node 4.1.1 and was able to replicate the steps and full test suite pass.

When I switched to `master` branch though, I could not complete `npm run build`, even using older Node versions.  Error:

```shell
demo$ npm run build

> readium-cfi-js@0.24.0 prebuild /private/tmp/readium-cfi-js
> npm run clean


> readium-cfi-js@0.24.0 clean /private/tmp/readium-cfi-js
> node --version && npm --version && node ./node_modules/rimraf/bin.js build-output/* && node ./node_modules/rimraf/bin.js api-docs/* && node ./node_modules/rimraf/bin.js gen/*

v0.12.15
2.15.1

> readium-cfi-js@0.24.0 build /private/tmp/readium-cfi-js
> npm run build:scripts


> readium-cfi-js@0.24.0 prebuild:scripts /private/tmp/readium-cfi-js
> npm run build:scripts:peg


> readium-cfi-js@0.24.0 build:scripts:peg /private/tmp/readium-cfi-js
> node ./node_modules/pegjs/bin/pegjs --export-var window.EPUBcfiParser cfi_parser.pegjs gen/cfi_parser_gen.js

Can't use the -e/--export-var option with the "commonjs" module format.

npm ERR! Darwin 14.5.0

[...SNIPPED...]
```
I didn't see any Travis jobs for `master`, so didn't go any farther with it.

To be thorough, I tested #566 again using Node 4.1.1, and the error persisted (which makes sense since it's not a problem related to peer dependencies).

**Comment by danielweck** [comment]
ah, we need to cherry pick a develop fix to master! thanks for pointing this out (and for all your tests)

**Comment by da70** [comment]
Sure, glad I could help.

**Pull request closed without merging**
