### PR TITLE
Fixes #357 arrow key nav. in TOC

### LINKED ISSUE #357: Implement arrow key navigation in ToC
It is awkward to have to tab through every item in the ToC - arrow key navigation while no less keystrokes to navigate, would allow tabbing into and out of the ToC. 

This is related to #212 - arrow key navigation would be the first step to a tree implementation of the ToC

### PR DESCRIPTION
**Pull request by becka11y**
The up, down, end, and home arrow keys can be used to navigate the TOC rather than tab.
The TOC close button is left in the tab order but other items are navigated via arrow
keys. When a new item is loaded, focus remains in the TOC if it is open. Each time the TOC is
opened via the keyboard, focus starts on the TOC close button.

### CODE REVIEW

**Comment by danielweck** [comment]
Thanks Becky!
I like the `home` + `end` button, but the `up` + `down` arrow keys trigger a vertical scroll shift at the same time as the TOC heading keyboard focus. This makes the scrolling viewport "jumpy". I will continue testing :)

**Comment by danielweck** [comment]
A good way to reproduce the vertical viewport scrolling behaviour is to long-press the down arrow when the focused TOC heading is a the top (for example in the "accessible EPUB3" ebook, which has a long TOC). The scrolling viewport starts to scroll down, and when the arrow key is released, the TOC heading gains keyboard focus (scroll all the way up).

**Comment by becka11y** [comment]
Hi, Daniel,
Now that I have prevented the scrolling, is it still too jumpy? There is a bit of "jump" when the viewport finally does scroll to keep the current item in focus.
The other issue is that the browser status popups to display the focused/mouse over link, cover up the actual ToC entry in some browsers.  I'm not sure it is worth working around default browser behavior, though.

**Comment by danielweck** [comment]
Thanks Becky. Looks good to me (normal web browser "bring/scroll into view" behaviour, and yes, in some browsers the overlay-style status bar in the lower-left is intrusive...nothing we can / should do about it, IMO). As expected, the `space` bar (+optional `shift`) invokes paged scrolling. Pressing `enter` activates hyperlinks. The `tab` key exits the TOC, putting focus into the content `iframe`. Pressing `t` brings focus to the TOC area (shows it if not already displayed). LGTM

**Pull request merged**
