### PR TITLE
bulk ebook import

### PR DESCRIPTION
**Pull request by danielweck**
Multiple EPUB import (Chrome app ebook library), with error handling and cancellable sequence. Works with drag-and-drop as well as the file picker dialog.

### CODE REVIEW

**Comment by danielweck** [comment]
CC @brettins

**Comment by danielweck** [comment]
Note that the per-EPUB progress bar is now a proper modal dialog (Twitter Bootstrap), whereas before it could be discarded by clicking outside the dialog (even though the WebWorker / background thread was continuing to import the ebook into the library).

Also note that there is a cancel button to stop the sequence of imported EPUBs, but a currently-importing EPUB still cannot be interrupted (i.e. no functional / behaviour change compared to code in the develop branch).

**Comment by danielweck** [comment]
Another note: the selected list of files to import into the ebooks library may contain non-EPUB files (e.g. drag-and-drop of a bunch of random files onto the Chrome apps' window, or erroneous user selection from the system file picker). This is handled appropriately by this PR implementation: the culprit non-EPUB files are ignored. 
Equally, there's graceful degradation if an error occurs during the loading of a given EPUB: the ebook is skipped, and the import queue moves to the next available EPUB file.

**Comment by rkwright** [comment]
@danielweck I have tested the feature branch on both OSX and Windows 10 (under Parallels).  Tested with a variety of files, both valid and invalid, large and small.  Looks good!  Will merge.

**Pull request merged**
